# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Returns whether the given command is executable or aliased.
_has() {
  return $( whence $1 >/dev/null )
}

_append_to_path() {
  if [ -d $1 -a -z ${path[(r)$1]} ]; then
    path=($1 $path);
  fi
}

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robin"

# Which plugins would you like to load?
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions)

# User configuration
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $ZSH/oh-my-zsh.sh

export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH

# Aliases
source ~/.aliases

# Private rc file for non-checked-in rc scripts
source ~/.secretrc

# Bash Functions
source ~/.helpers.sh
source ~/.goto.sh

# Default Editor
export EDITOR=vim

# openssl
export PATH="$(brew --prefix openssl@3.5)/bin:$PATH"
export LDFLAGS="-L$(brew --prefix openssl@3.5)/lib"
export CPPFLAGS="-I$(brew --prefix openssl@3.5)/include"
export PKG_CONFIG_PATH="$(brew --prefix openssl@3.5)/lib/pkgconfig"
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3.5)"

# postgres
export PATH="$(brew --prefix postgresql@14)/bin:$PATH"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then
  eval "$(rbenv init -)";
fi

# nodenv
eval "$(nodenv init -)"

# pyenv
# https://github.com/pyenv/pyenv#basic-github-checkout
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PYTHON_CONFIGURE_OPTS="--enable-framework"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# .inputrc
bindkey '^[OA' history-beginning-search-backward
bindkey '^[OB' history-beginning-search-forward

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
if _has fzf && _has rg; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export DISABLE_SPRING=true
source /Users/sjl2/.config/op/plugins.sh
eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH="$HOME/.local/bin:$PATH"
